[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"


[server]
port = 5401
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats = false